### ISSUE TITLE
AddAdmin.py fails due to no module found

### ISSUE THREAD

**Issue by CanBusHack** [linted/HardwareCheckout#91]
ModuleNotFoundError: No module named 'tornado_sqlalchemy'

Probably need to make sure we add that to Requirements file.

**Comment by CanBusHack** [comment]
Also:

ModuleNotFoundError: No module named 'HardwareCheckout.config'

**Comment by 5hu5ky** [comment]
tornado-sqlalchemy==0.7.0 is in the requirements.txt since April...

AddAdmin.py works on both dev and prod the environments - please make sure you clean all artifacts from prior installs and try again.

Also make sure you activate the virtual environment before you run addAmin.py as all the libs are installed with reference to that virtual environment... 

`cd /opt/HardwareCheckout`
`source ./venv/bin/activate`
`python3 addAdmin.py username password`
